### ISSUE TITLE
MySQL connection error

### ISSUE THREAD

**Issue by jquadrin** [liveforeverx/mariaex#1]
```
18:38:11.339 [error] GenServer #PID<0.88.0> terminating
Last message: {:connect, %{hostname: "localhost", password: nil, port: "3306", user: "root"}}
State: %{backend_key: nil, opts: nil, parameters: %{}, queue: {[], []}, rows: [], seqnum: 0, sock: nil, sock_mod: Mariaex.Connection.Tcp, state: :ready, statement: nil, tail: "", transactions: 0, types: :types_removed}
** (exit) an exception was raised:
    ** (ErlangError) erlang error: {:function_clause, [{:inet_tcp, :getserv, ["3306"], [file: 'inet_tcp.erl', line: 35]}, {:gen_tcp, :connect1, 4, [file: 'gen_tcp.erl', line: 154]}, {:gen_tcp, :connect, 4, [file: 'gen_tcp.erl', line: 141]}, {Mariaex.Connection, :handle_call, 3, [file: 'lib/mariaex/mariaex.ex', line: 289]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 607]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 639]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}
        (kernel) gen_tcp.erl:146: :gen_tcp.connect/4
        (mariaex) lib/mariaex/mariaex.ex:289: Mariaex.Connection.handle_call/3
        (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

**Comment by liveforeverx** [comment]
Hi! That is because port is integer, not a string...(3306 is default)

The postgrex adaptor crashed with same error too.

But may be, there type checking for options needed? Or what would be best solution for this crash for you?

**Comment by liveforeverx** [comment]
Hi! That is because port is integer, not a string...(3306 is default)

The postgrex adaptor crashed with same error too.

But may be, there type checking for options needed? Or what would be best solution for this crash for you?

**Comment by liveforeverx** [comment]
Hi! That is because port is integer, not a string...(3306 is default)

The postgrex adaptor crashed with same error too.

But may be, there type checking for options needed? Or what would be best solution for this crash for you?

**Comment by liveforeverx** [comment]
Hi! That is because port is integer, not a string...(3306 is default)

The postgrex adaptor crashed with same error too.

But may be, there type checking for options needed? Or what would be best solution for this crash for you?

**Comment by liveforeverx** [comment]
Hi! That is because port is integer, not a string...(3306 is default)

The postgrex adaptor crashed with same error too.

But may be, there type checking for options needed? Or what would be best solution for this crash for you?

**Comment by liveforeverx** [comment]
Sorry, because of worst internet connection, the message was sent many times.

**Comment by jquadrin** [comment]
I fixed that but I still consistently get 
```elixir
Mariaex.Connection.start_link(%{user: "root", port: 3306})
** (exit) exited in: GenServer.call(#PID<0.79.0>, {:connect, %{hostname: "localhost", password: nil, port: 3306, user: "root"}}, 5000)
    ** (EXIT) time out
     (elixir) lib/gen_server.ex:356: GenServer.call/3
    (mariaex) lib/mariaex/mariaex.ex:62: Mariaex.Connection.start_link/1
```

**Comment by jquadrin** [comment]
and this
```elixir
iex(1)> Mariaex.Connection.start_link(%{user: "root"})
** (EXIT from #PID<0.126.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.byte_size(nil)
        (mariaex) lib/mariaex/messages.ex:89: Mariaex.Messages.encode_handshake_resp/1
        (mariaex) lib/mariaex/messages.ex:160: Mariaex.Messages.encode/2
        (mariaex) lib/mariaex/protocol.ex:109: Mariaex.Protocol.msg_send/3
        (mariaex) lib/mariaex/protocol.ex:38: Mariaex.Protocol.dispatch/2
        (mariaex) lib/mariaex/mariaex.ex:390: Mariaex.Connection.process/2
        (mariaex) lib/mariaex/mariaex.ex:317: Mariaex.Connection.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
```

**Comment by jquadrin** [comment]
this works
```elixir
iex(2)> Mariaex.Connection.start_link(%{user: "root", database: "ecto_test"})
{:ok, #PID<0.115.0>}
```

**Comment by liveforeverx** [comment]
Ok, close for now. If you want to have better errors for some use cases, please let me know.
